using System;
using System.Collections.Generic;

#nullable disable

namespace MigrationIssueSample.Entities
{
    public partial class UserActiveSkill
    {
        public int CharId { get; set; }
        public int? S1 { get; set; }
        public byte? L1 { get; set; }
        public int? D1 { get; set; }
        public int? S2 { get; set; }
        public byte? L2 { get; set; }
        public int? D2 { get; set; }
        public int? S3 { get; set; }
        public byte? L3 { get; set; }
        public int? D3 { get; set; }
        public int? S4 { get; set; }
        public byte? L4 { get; set; }
        public int? D4 { get; set; }
        public int? S5 { get; set; }
        public byte? L5 { get; set; }
        public int? D5 { get; set; }
        public int? S6 { get; set; }
        public byte? L6 { get; set; }
        public int? D6 { get; set; }
        public int? S7 { get; set; }
        public byte? L7 { get; set; }
        public int? D7 { get; set; }
        public int? S8 { get; set; }
        public byte? L8 { get; set; }
        public int? D8 { get; set; }
        public int? S9 { get; set; }
        public byte? L9 { get; set; }
        public int? D9 { get; set; }
        public int? S10 { get; set; }
        public byte? L10 { get; set; }
        public int? D10 { get; set; }
        public int? S11 { get; set; }
        public byte? L11 { get; set; }
        public int? D11 { get; set; }
        public int? S12 { get; set; }
        public byte? L12 { get; set; }
        public int? D12 { get; set; }
        public int? S13 { get; set; }
        public byte? L13 { get; set; }
        public int? D13 { get; set; }
        public int? S14 { get; set; }
        public byte? L14 { get; set; }
        public int? D14 { get; set; }
        public int? S15 { get; set; }
        public byte? L15 { get; set; }
        public int? D15 { get; set; }
        public int? S16 { get; set; }
        public byte? L16 { get; set; }
        public int? D16 { get; set; }
        public int? S17 { get; set; }
        public byte? L17 { get; set; }
        public int? D17 { get; set; }
        public int? S18 { get; set; }
        public byte? L18 { get; set; }
        public int? D18 { get; set; }
        public int? S19 { get; set; }
        public byte? L19 { get; set; }
        public int? D19 { get; set; }
        public int? S20 { get; set; }
        public byte? L20 { get; set; }
        public int? D20 { get; set; }
        public int? S21 { get; set; }
        public byte? L21 { get; set; }
        public int? D21 { get; set; }
        public int? S22 { get; set; }
        public byte? L22 { get; set; }
        public int? D22 { get; set; }
        public int? S23 { get; set; }
        public byte? L23 { get; set; }
        public int? D23 { get; set; }
        public int? S24 { get; set; }
        public byte? L24 { get; set; }
        public int? D24 { get; set; }
        public int? S25 { get; set; }
        public byte? L25 { get; set; }
        public int? D25 { get; set; }
        public int? S26 { get; set; }
        public byte? L26 { get; set; }
        public int? D26 { get; set; }
        public int? S27 { get; set; }
        public byte? L27 { get; set; }
        public int? D27 { get; set; }
        public int? S28 { get; set; }
        public byte? L28 { get; set; }
        public int? D28 { get; set; }
        public int? S29 { get; set; }
        public byte? L29 { get; set; }
        public int? D29 { get; set; }
        public int? S30 { get; set; }
        public byte? L30 { get; set; }
        public int? D30 { get; set; }
        public int? S31 { get; set; }
        public byte? L31 { get; set; }
        public int? D31 { get; set; }
        public int? S32 { get; set; }
        public byte? L32 { get; set; }
        public int? D32 { get; set; }
        public int? S33 { get; set; }
        public byte? L33 { get; set; }
        public int? D33 { get; set; }
        public int? S34 { get; set; }
        public byte? L34 { get; set; }
        public int? D34 { get; set; }
        public int? S35 { get; set; }
        public byte? L35 { get; set; }
        public int? D35 { get; set; }
        public int? S36 { get; set; }
        public byte? L36 { get; set; }
        public int? D36 { get; set; }
        public int? S37 { get; set; }
        public byte? L37 { get; set; }
        public int? D37 { get; set; }
        public int? S38 { get; set; }
        public byte? L38 { get; set; }
        public int? D38 { get; set; }
        public int? S39 { get; set; }
        public byte? L39 { get; set; }
        public int? D39 { get; set; }
        public int? S40 { get; set; }
        public byte? L40 { get; set; }
        public int? D40 { get; set; }
        public byte? C1 { get; set; }
        public byte? C2 { get; set; }
        public byte? C3 { get; set; }
        public byte? C4 { get; set; }
        public byte? C5 { get; set; }
        public byte? C6 { get; set; }
        public byte? C7 { get; set; }
        public byte? C8 { get; set; }
        public byte? C9 { get; set; }
        public byte? C10 { get; set; }
        public byte? C11 { get; set; }
        public byte? C12 { get; set; }
        public byte? C13 { get; set; }
        public byte? C14 { get; set; }
        public byte? C15 { get; set; }
        public byte? C16 { get; set; }
        public byte? C17 { get; set; }
        public byte? C18 { get; set; }
        public byte? C19 { get; set; }
        public byte? C20 { get; set; }
        public byte? C21 { get; set; }
        public byte? C22 { get; set; }
        public byte? C23 { get; set; }
        public byte? C24 { get; set; }
        public byte? C25 { get; set; }
        public byte? C26 { get; set; }
        public byte? C27 { get; set; }
        public byte? C28 { get; set; }
        public byte? C29 { get; set; }
        public byte? C30 { get; set; }
        public byte? C31 { get; set; }
        public byte? C32 { get; set; }
        public byte? C33 { get; set; }
        public byte? C34 { get; set; }
        public byte? C35 { get; set; }
        public byte? C36 { get; set; }
        public byte? C37 { get; set; }
        public byte? C38 { get; set; }
        public byte? C39 { get; set; }
        public byte? C40 { get; set; }
    }
}
